<?php
/*
 * ===========================================================================
 * API 기준 정보 설정
 * ===========================================================================
 *
 * API서버로 접근 내용을 메소드로 구성해서 include해서 사용하면 됩니다.
 *
 * ---------------------------------------------------------------------------
 * 작성자: 리성림 <chenglin@smileserv.com>
 * 작성일: 2018년 06월 07일
 * ===========================================================================
 */
$_API = array
(
	/**
	 * apiDomain
	 * API서버 도메인
	 * 'https://' 부터 시작합니다.
	 */
	'apiDomain' => 'https://console.cav.iwinv.kr/api',

	/**
	 * accesskeyId
	 * accesskey ID
	 */
	'accesskeyId' => 'K1u1D959P0HxKRR65O7kVk37N29xOB67',

	/**
	 * accesskeySecret
	 * accesskey 비번
	 */
	'accesskeySecret' => 'z8o1a75SMyOPCZ90D73tY7j9f6ygcaD7',

	/**
	 * folderKey
	 * 스토리지키 또는 폴더키
	 */
	'folderKey' => 'ry1Ey5894kmAL8ylsU9i47sHy77PJnH6',

	/**
	 * version
	 * API 버전
	 */
	'version' => 'v1'
) ;
